version: '3'
services:
  frontend:
    build: PollBuddy-Server/frontend
    restart: unless-stopped
    ports:
      - "7655:80"
    networks:
      - backend
      - logging

  backend:
    build: PollBuddy-Server/backend
    restart: unless-stopped
    networks:
      - backend
  
  db:
    image: "mongo:4"
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    networks:
      - backend

  grafana:
    build: PollBuddy-Server/reporting/grafana
    restart: unless-stopped
    networks:
      - logging

  influxdb:
    build: PollBuddy-Server/reporting/influxdb
    restart: unless-stopped
    volumes:
      - influxdata:/var/lib/influxdb
    networks:
      - logging
      - backend

volumes:
  mongoconfig:
    external: false

  mongodata:
    external: false

  influxdata:
    external: false

networks:
  backend:
  logging:


