version: '3'
services:
  frontend:
    build:
      context: PollBuddy-Server/frontend
      dockerfile: "Dockerfile.test"

  backend:
    build:
      context: PollBuddy-Server/backend
      dockerfile: "Dockerfile.test"

  db:
    image: "mongo:4"
    restart: unless-stopped
    volumes:
      - test_mongodata:/data/db
      - test_mongoconfig:/data/configdb
    networks:
      - backend

volumes:
  test_mongoconfig:
    external: false

  test_mongodata:
    external: false