apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: poll-buddy
  name: poll-buddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy
    spec:
      containers:
        - image: pollbuddy/frontend:kubernetes-setup
          name: frontend
          ports:
            - containerPort: 80
              -
        - image: pollbuddy/backend:kubernetes-setup
          name: backend

        - image: mongo:4
          name: db

        - image: pollbuddy/reporting:kubernetes-setup
          name: reporting

        - image: pollbuddy/reporting-db:kubernetes-setup
          name: reporting-db
