# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-backend-service-master
  labels:
    app.kubernetes.io/name: poll-buddy-backend-service-master
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: backend
  selector:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
  type: NodePort

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
  name: poll-buddy-backend-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: poll-buddy
      app.kubernetes.io/instance: master
      app: poll-buddy-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: poll-buddy
        app.kubernetes.io/instance: master
        app: poll-buddy-backend
    spec:
      restartPolicy: Always
      containers:
        - image: pollbuddy/backend:kubernetes-setup
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3001
              name: backend
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/healthcheck
              port: 3001
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            # TODO: Health check probe
