# ConfigMap to store the non-secret database details
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poll-buddy-backend-configmap-master
  labels:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
data:
  frontend_url: http://localhost:7655
  session_secret: NTpUkD6xyALq4LMB2FDHf2iKdYcSznns
