apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: poll-buddy-backend-secrets-master
  labels:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
data:
  # This should be changed
  session_secret: TlRwVWtENnh5QUxxNExNQjJGREhmMmlLZFljU3pubnM=