# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-backend-service-master
  labels:
    app.kubernetes.io/name: poll-buddy-backend-service-master
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: backend
  selector:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
  type: ClusterIP

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-backend
  name: poll-buddy-backend-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: poll-buddy
      app.kubernetes.io/instance: master
      app: poll-buddy-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: poll-buddy
        app.kubernetes.io/instance: master
        app: poll-buddy-backend
    spec:
      restartPolicy: Always
      containers:
        - image: pollbuddy/backend:kubernetes-setup
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3001
              name: backend
          env:
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-backend-configmap-master
                  key: frontend_url
            - name: DB_URL
              value: poll-buddy-db-service-master.default.svc.cluster.local
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-db-configmap-master
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-db-configmap-master
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-db-secrets-master
                  key: user-password
            - name: REPORTING_DB_URL
              value: poll-buddy-reporting-db-service-master.default.svc.cluster.local
            - name: REPORTING_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-reporting-db-configmap-master
                  key: reporting_db_name
            - name: REPORTING_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-reporting-db-configmap-master
                  key: reporting_db_username
            - name: REPORTING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-reporting-db-secrets-master
                  key: user-password
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-backend-configmap-master
                  key: session_secret
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/healthcheck
              port: 3001
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            # TODO: Health check probe
