apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: poll-buddy-db-secrets-master
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
    app: poll-buddy-db
data:
  # ThisRootPasswordShouldBeChanged
  admin-password: VGhpc1Jvb3RQYXNzd29yZFNob3VsZEJlQ2hhbmdlZA==
  # ThisUserPasswordShouldBeChanged
  user-password: VGhpc1VzZXJQYXNzd29yZFNob3VsZEJlQ2hhbmdlZA==