# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-frontend-service-master
  labels:
    app.kubernetes.io/name: poll-buddy-frontend-service-master
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: frontend
  selector:
    app.kubernetes.io/name: poll-buddy-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-frontend
  type: NodePort

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: poll-buddy-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-frontend
  name: poll-buddy-frontend-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-frontend
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: poll-buddy
      app.kubernetes.io/instance: master
      app: poll-buddy-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: poll-buddy
        app.kubernetes.io/instance: master
        app: poll-buddy-frontend
    spec:
      restartPolicy: Always
      containers:
        - image: pollbuddy/frontend:kubernetes-setup
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
              name: frontend
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: BACKEND
              value: poll-buddy-backend-service-master
            - name: REPORTING
              value: poll-buddy-reporting-service-master
