# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: poll-buddy-reporting
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-reporting
  name: poll-buddy-reporting-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-reporting
      app.kubernetes.io/component: reporting
      app.kubernetes.io/part-of: poll-buddy
      app.kubernetes.io/instance: master
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-reporting
        app.kubernetes.io/component: reporting
        app.kubernetes.io/part-of: poll-buddy
        app.kubernetes.io/instance: master
    spec:
      restartPolicy: Always
      containers:
        - image: pollbuddy/reporting:kubernetes-setup
          name: reporting
          ports:
            - containerPort: 300
              name: reporting-port

# Create a service to access the app from outside the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-reporting-service-master
  labels:
    app.kubernetes.io/name: poll-buddy-reporting-service-master
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: master
    app: poll-buddy-reporting
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: reporting-port
  selector:
    app.kubernetes.io/name: poll-buddy-reporting-deployment-master
  type: NodePort
