# Allocate a volume for data storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poll-buddy-volume-claim-influx-master
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: reporting-db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
    app: poll-buddy-reporting-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-reporting-db-service-master
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: reporting-db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
    app: poll-buddy-reporting-db
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: reporting-db
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: reporting-db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
    app: poll-buddy-reporting-db
  type: ClusterIP

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: reporting-db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
  name: poll-buddy-reporting-db-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/component: reporting-db
      app.kubernetes.io/part-of: poll-buddy
      environment: production
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/component: reporting-db
        app.kubernetes.io/part-of: poll-buddy
        environment: production
    spec:
      restartPolicy: Always
      containers:
        - name: reporting-db
          image: pollbuddy/reporting-db:kubernetes-setup
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
              name: reporting-db
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: db-influx
      volumes:
        - name: db-influx
          persistentVolumeClaim:
            claimName: pollbuddy-volume-claim-influx-master
