apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: poll-buddy-reporting-db-secrets-master
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: reporting-db
    app.kubernetes.io/part-of: poll-buddy
    environment: production
    app: poll-buddy-reporting-db
data:
  # pollbuddy
  admin-password: cG9sbGJ1ZGR5
  # pollbuddy
  user-password: VGhpc1VzZXJQYXNzd29yZFNob3VsZEJlQ2hhbmdlZA==