name: CI-PullRequest

on:
  pull_request:

jobs:
  PullRequest-Comment:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Share Link on PR
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v1.0.4
        with:
          message: |
            Live version is available!
            Always-Updated URL: https://dev-${{ github.event.number }}.pollbuddy.app/
            
            Last commit: ${{ github.event.pull_request.head.sha }}
            Up-To-Commit URL: https://dev-${{ github.event.pull_request.head.sha }}.pollbuddy.app/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
